# Generated by Django 6.0.6 on 2026-09-24 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax/GST Number')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=60, unique=True, verbose_name='SKU / Item Code')),
                ('barcode', models.CharField(blank=True, max_length=80, null=True)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces (pcs)'), ('KG', 'Kilograms (kg)'), ('GM', 'Grams (gm)'), ('LTR', 'Liters (ltr)'), ('MTR', 'Meters (mtr)'), ('BOX', 'Boxes (box)'), ('PKT', 'Packets (pkt)'), ('SET', 'Sets (set)'), ('UNIT', 'Units (unit)')], default='PCS', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Purchase / Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Selling Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('current_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Current Stock')),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12, verbose_name='Min Reorder Level')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Stock In (Purchase)'), ('OUT_SALE', 'Stock Out (Invoice / Sale)'), ('ADJ_ADD', 'Manual Adjustment (+)'), ('ADJ_SUB', 'Manual Adjustment (-)'), ('RETURN_CUSTOMER', 'Customer Return (+)'), ('RETURN_SUPPLIER', 'Supplier Return (-)'), ('DAMAGE', 'Damaged / Expired (-)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('resulting_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_number', models.CharField(blank=True, help_text='e.g. Invoice #, PO #, Reason', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
